name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react-version:
          - '^16'
          - '^18'
          - '^19'
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - id: setup-react
        name: Setup React
        uses: ./
        with:
          react-version: ${{ matrix.react-version }}
          react-dom-version: ${{ matrix.react-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test action
        run: |
          if [[ "${{ steps.setup-react.outputs.react-version }}" != ${{ matrix.react-version }}* ]]; then
            exit 1
          fi
          if [[ "${{ steps.setup-react.outputs.react-dom-version }}" != ${{ matrix.react-version }}* ]]; then
            exit 1
          fi
          if [[ "${{ steps.setup-react.outputs.react-types-version }}" != "" ]]; then
            exit 1
          fi
          if [[ "${{ steps.setup-react.outputs.react-dom-types-version }}" != "" ]]; then
            exit 1
          fi
      - if: ${{ matrix.react-version == '^19' }}
        name: Check formatting
        run: npm run lint
      - if: ${{ matrix.react-version == '^19' }}
        name: Check types
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Check dist for changes
        run: git diff --exit-code --quiet ./dist
